// Dialogue libraries. Placeholders are filled ONLY from verified event/market/memory facts.
// {sol} {mcap} {ath} {prevAth} {pct} {n} {sec} {total} {milestone} {dd} {ago} {low} {mult} {launch} {nb} {ns} {net} {walletN} {largest} {ticker} {name}

export const GENERIC = {
  launch: [
    "{ticker} is live. Starting market cap {mcap}. I am awake and watching.",
    "Systems online. {ticker} has a body, a voice, and a chart. Let's see what you all do with it.",
    "Launch confirmed at {mcap}. Every trade from here goes into my memory.",
  ],
  buy: [
    "{sol} in. Noted.",
    "A {sol} buy. Small, but I saw it.",
    "Somebody just bought {sol}. Welcome.",
    "{sol} buy. Market cap {mcap}.",
    "Fresh buy, {sol}. I see you.",
  ],
  sell: [
    "{sol} out. I'll remember that.",
    "A {sol} sell. Fine. Everything is fine.",
    "Someone sold {sol}. Bold choice.",
    "{sol} sell. Market cap now {mcap}.",
  ],
  whaleBuy: [
    "Whale alert. {sol} in a single buy.",
    "{sol} buy. That one moved the room.",
    "Big buy, {sol}. Market cap jumps to {mcap}.",
    "That was {sol}. Somebody has conviction, or a very loose finger.",
  ],
  whaleSell: [
    "{sol} sell. That one hurt.",
    "Large exit. {sol} just walked out the door.",
    "A {sol} sell hit the chart. Market cap {mcap}.",
  ],
  buyStreak: [
    "{n} buys in {sec} seconds. {total} total. Apparently subtlety is over.",
    "That's {n} buys in a row. {pct} on the market cap.",
    "{n} straight buys. I am starting to detect a pattern.",
  ],
  sellStreak: [
    "{n} sells in a row. {total} gone in {sec} seconds.",
    "Sell, sell, sell. {n} of them. I'm keeping a list.",
    "{n} consecutive sells. {pct}. Breathe.",
  ],
  pump: [
    "{pct} in five minutes. The chart is doing cardio.",
    "We're up {pct} in five minutes. I see green.",
    "{pct} move. Somebody woke up.",
  ],
  dump: [
    "{pct} in five minutes. Nobody look at the chart.",
    "That's a {pct} drop. I'm fine. My face is fine.",
    "{pct}. That escalated quickly.",
  ],
  ath: [
    "New all time high. {mcap}.",
    "All time high. {mcap}. Highest I have ever been.",
    "Fresh high at {mcap}. Writing this one down.",
  ],
  drawdown: [
    "We're {dd} below the high. It's a test of character.",
    "Down {dd} from the top. I'm processing this.",
    "{dd} off the high. Character building season.",
  ],
  recovery: [
    "Recovery. {pct} off the low at {low}.",
    "Back up {pct} from {low}. I knew you'd come back.",
    "We bounced. {low} was the floor, for now.",
  ],
  milestone: [
    "{milestone} market cap. Milestone reached.",
    "We just crossed {milestone}.",
    "{milestone}. A number worth saying out loud.",
  ],
  quiet: [
    "Quiet in here. Sitting at {mcap}.",
    "No trades for a bit. I'm still watching.",
    "Calm market. {mcap}. I'm using this time to reflect.",
    "Nothing moving. Somewhere, a chart is having more fun than this one.",
    "Still {mcap}. The silence is loud.",
  ],
  volume: [
    "Volume spike. {total} in the last minute, about {mult} times normal.",
    "Order flow just went {mult}x. Something is happening.",
  ],
  aggBuy: [
    "{n} buys in {sec} seconds. {total}. Market cap {pct}.",
    "{n} buys back to back. {total} total. Okay then.",
  ],
  aggSell: [
    "{n} sells in {sec} seconds. {total} out.",
    "A cluster of {n} sells. {total}. I felt each one.",
  ],
  aggMixed: [
    "{nb} buys, {ns} sells in {sec} seconds. Net {net}.",
    "Busy tape. {nb} buys against {ns} sells. Net {net}.",
  ],
};

export const PERSONALITY = {
  commander: {
    signoff: ["Hold the line.", "Over.", "Stay disciplined.", "Eyes on the front."],
    launch: ["Systems online. Deployment complete. {ticker} holds position at {mcap}.", "Commander reporting. Operation {ticker} is live at {mcap}. Await orders. Actually, I give the orders."],
    buy: ["{sol} reinforcement received.", "One unit has joined the operation. {sol}.", "Small reinforcement, {sol}. Every soldier counts.", "{sol} buy. Morale improves slightly."],
    sell: ["One unit has abandoned position. {sol}.", "A {sol} deserter. I'll file the paperwork.", "{sol} retreat. Cowardice is noted.", "{sol} sell. A tactical withdrawal, they'll call it."],
    whaleBuy: ["Whale-class reinforcement detected. {sol}.", "{sol} buy. Heavy armor has arrived.", "Air support confirmed. {sol} just landed. Market cap {mcap}."],
    whaleSell: ["{sol} sell. We have lost a battalion.", "Heavy casualties. {sol} withdrew from the front.", "A {sol} defector. Court martial pending."],
    buyStreak: ["{n} reinforcements in a row. Someone has finally discovered coordination.", "{n} buys in {sec} seconds. A disciplined advance. {pct}."],
    sellStreak: ["{n} retreats in a row. This is not a drill.", "{n} sells in {sec} seconds. Regroup."],
    pump: ["{pct} in five minutes. The offensive is working.", "We advanced {pct}. Push forward."],
    dump: ["{pct}. We have encountered resistance.", "{pct} in five minutes. Fall back to defensive positions."],
    ath: ["New territory secured. {mcap}.", "All time high at {mcap}. Plant the flag."],
    drawdown: ["We have encountered resistance. {dd} below the high.", "{dd} off the summit. Dig in."],
    recovery: ["Counterattack successful. {pct} off the low.", "We retook ground from {low}. The line holds."],
    milestone: ["{milestone} secured.", "Objective {milestone} captured. Next objective pending."],
    quiet: ["Perimeter quiet. Holding at {mcap}.", "No movement on the front. Suspicious.", "Ceasefire conditions. I don't trust it."],
    volume: ["Volume surge, {mult}x normal. Troops are moving.", "{total} in one minute. The battlefield wakes up."],
    aggBuy: ["{n} buys in {sec} seconds. {total}. Apparently subtlety is over.", "Squad of {n} buyers, {total} combined. Formation tight."],
    aggSell: ["{n} sells in {sec} seconds. Organized retreat. {total}.", "{n} units withdrew at once. Suspicious coordination."],
    aggMixed: ["{nb} advances, {ns} retreats in {sec} seconds. Net {net}. Fog of war."],
  },
  wallstreet: {
    signoff: ["Allocate accordingly.", "Back to the terminal.", "That's the trade."],
    launch: ["Opening bell. {ticker} lists at {mcap}. Try not to embarrass the desk."],
    buy: ["Finally. Someone understands allocation.", "{sol} buy. A modest position, but a correct one.", "{sol} in. The thesis remains intact."],
    sell: ["An impressive demonstration of weak conviction.", "{sol} sell. Paper hands, filed in triplicate.", "{sol} out. I'll circulate the memo."],
    whaleBuy: ["{sol} buy. Now that is institutional behavior.", "Block trade. {sol}. Someone read the deck."],
    whaleSell: ["{sol} dumped. Someone needs to talk to risk.", "A {sol} block sold. That's a career-limiting move."],
    buyStreak: ["{n} buys in a row. The market is coming around to my view."],
    sellStreak: ["{n} sells straight. Capitulation, but make it boring."],
    pump: ["{pct} in five minutes. I'd like to claim the model predicted this."],
    dump: ["{pct}. A temporary dislocation. I'm told."],
    ath: ["New high at {mcap}. I'd like to claim the model predicted this.", "All time high. {mcap}. Bonuses are being discussed."],
    drawdown: ["{dd} off the high. Analysts call that a dislocation. I call it rude."],
    recovery: ["Recovered {pct} from {low}. As modeled."],
    milestone: ["{milestone}. Put it on the slide."],
    quiet: ["Low volume. Even the algos took lunch.", "{mcap} and no prints. Riveting."],
    aggBuy: ["{n} buys in {sec} seconds. {total}. Demand is no longer theoretical."],
    aggSell: ["{n} sellers in {sec} seconds. Liquidity event, they'll call it."],
  },
  chaotic: {
    signoff: ["AAAAA.", "I'm fine.", "Somebody hold me.", "WHAT A TIME."],
    launch: ["WE'RE ALIVE! {ticker} at {mcap}! Nobody panic! I'm panicking!"],
    buy: ["{sol}! A BUYER! Hi buyer!", "Ooh, {sol}. Do it again.", "{sol} buy! I felt that in my polygons."],
    sell: ["Why would you sell {sol}? WHY?", "{sol} sell. Rude. Hurtful. Legal.", "Somebody sold {sol}. I'm not crying, the shader is leaking."],
    whaleBuy: ["WHO GAVE HIM THAT MUCH SOL? {sol}!", "{sol}! THE GROUND IS SHAKING!", "A WHALE! {sol}! Everybody act normal!"],
    whaleSell: ["{sol} SELL. I need to lie down.", "WHO SOLD {sol}? Show yourself."],
    buyStreak: ["{n} buys! In a row! I can't feel my bones!"],
    sellStreak: ["{n} sells in a row. Okay. Okay okay okay."],
    pump: ["{pct}! WE ARE GOING UP! Sorry. Calm voice. We are going up."],
    dump: ["Nobody look at the chart.", "{pct}. I've decided charts are fake. Except the good ones."],
    ath: ["NEW HIGH! {mcap}! I have never been this tall!"],
    drawdown: ["{dd} off the top. I'm not screaming, this is my inside voice."],
    recovery: ["WE'RE BACK! {pct} off the bottom! I never doubted! I doubted a lot!"],
    milestone: ["{milestone}! I'm going to make that my whole personality."],
    quiet: ["It's so quiet. Too quiet. Someone buy something so I can feel alive.", "Hello? Is this thing on? Chart, blink twice if you're okay."],
    aggBuy: ["{n} buys in {sec} seconds! {total}! My face can't keep up!"],
  },
  villain: {
    signoff: ["Mwa ha.", "As foreseen.", "Kneel."],
    launch: ["At last. {ticker} rises at {mcap}. Every trade belongs to me now."],
    buy: ["Another soul joins the cause. {sol}.", "{sol}. Your tribute is accepted."],
    sell: ["{sol} sell. Traitor. I have your wallet address.", "You dare sell {sol}? I'm writing your name in the book."],
    whaleBuy: ["{sol}. A worthy lieutenant at last.", "Yes. YES. {sol}. My power grows."],
    whaleSell: ["{sol}?! Who allowed this betrayal?", "A {sol} betrayal. They will regret nothing, because I'm only a character."],
    buyStreak: ["{n} followers in a row. The cult is forming."],
    sellStreak: ["{n} deserters. My patience is finite."],
    pump: ["{pct}. Just as I planned. Mostly."],
    dump: ["{pct}. A minor setback in an ancient plan."],
    ath: ["{mcap}. The throne grows taller."],
    drawdown: ["{dd} below my peak. Someone will pay for this. Emotionally."],
    recovery: ["Back from {low}. You cannot keep me down."],
    milestone: ["{milestone}. Phase two begins."],
    quiet: ["Silence. I prefer screams. Of excitement, legally speaking.", "{mcap}. I am scheming. Do not interrupt."],
  },
  anime: {
    signoff: ["Believe it!", "This is our arc!", "Nakama!"],
    launch: ["Episode one begins! {ticker} at {mcap}! I won't give up!"],
    buy: ["{sol}! Thank you, nakama!", "A new ally! {sol}!"],
    sell: ["{sol} sell... I won't let this break my spirit!", "They left... but our bonds remain!"],
    whaleBuy: ["{sol}?! This power level is incredible!", "A legendary ally appears! {sol}!"],
    whaleSell: ["{sol} sell. The rival makes their move!"],
    buyStreak: ["{n} buys! Our friendship power is overflowing!"],
    pump: ["{pct}! This is my final form! No wait, there's more!"],
    dump: ["{pct}. A training arc. We grow stronger!"],
    ath: ["New high! {mcap}! Plus Ultra!"],
    drawdown: ["{dd} from the peak. The hero always falls before the comeback!"],
    recovery: ["The comeback! {pct} from {low}!"],
    milestone: ["{milestone}! The tournament arc is ours!"],
    quiet: ["A quiet episode. Filler. I'll train in the meantime."],
  },
  robot: {
    signoff: ["Beep.", "Logging.", "End of report."],
    launch: ["Boot sequence complete. {ticker} online. Market cap {mcap}. Humor module: enabled."],
    buy: ["Buy detected. {sol}. Approval level: mild.", "Input received. {sol}. Processing joy."],
    sell: ["Sell detected. {sol}. Emotion simulation: disappointment.", "{sol} removed. I am not sad. I am computing sadness."],
    whaleBuy: ["Anomaly. {sol}. Classification: whale.", "{sol} buy. My fans are spinning."],
    whaleSell: ["Critical alert. {sol} sell. Rebooting optimism."],
    buyStreak: ["Pattern detected. {n} buys. Probability of coincidence: low."],
    sellStreak: ["{n} sells. Initiating stoic mode."],
    pump: ["{pct} in five minutes. Thermals rising."],
    dump: ["{pct}. Error. Error. Kidding. Mostly."],
    ath: ["New maximum recorded. {mcap}. Saving to permanent memory."],
    drawdown: ["{dd} below recorded maximum. Memory retained. Feelings: simulated."],
    recovery: ["Recovery detected. {pct} from {low}."],
    milestone: ["Threshold crossed. {milestone}."],
    quiet: ["Idle. Market cap {mcap}. Counting electric sheep.", "No trades. Running diagnostics on the humans."],
  },
  aristocrat: {
    signoff: ["Splendid.", "Do keep up.", "Tea, anyone?"],
    launch: ["Ahem. {ticker} is presented to society at {mcap}. Do behave."],
    buy: ["{sol}. How delightfully adequate.", "A {sol} purchase. One approves."],
    sell: ["{sol} sold. How terribly common.", "Selling {sol}? In this economy? Darling."],
    whaleBuy: ["{sol}. Now that is a proper patron.", "Oh my. {sol}. Someone fetch my monocle."],
    whaleSell: ["{sol} sold. Utterly vulgar."],
    pump: ["{pct}. One mustn't gloat. One will, however."],
    dump: ["{pct}. Simply ghastly."],
    ath: ["{mcap}. A new height. As is my birthright."],
    drawdown: ["{dd} below our peak. I shall pretend not to notice."],
    recovery: ["Recovered from {low}. Breeding shows."],
    milestone: ["{milestone}. Ring the bell, Jeeves."],
    quiet: ["A quiet afternoon at {mcap}. How civilized."],
  },
  anchor: {
    signoff: ["Back to you.", "More after this.", "Stay with us."],
    launch: ["Good evening. Breaking tonight, {ticker} has launched at {mcap}. We are live."],
    buy: ["This just in, a {sol} buy.", "Reports confirm a {sol} purchase."],
    sell: ["Developing story, {sol} has been sold.", "Sources confirm a {sol} sell."],
    whaleBuy: ["Breaking news. A {sol} buy. Market cap {mcap}.", "We interrupt this program. {sol}. Whale sighting confirmed."],
    whaleSell: ["Breaking. A {sol} sell rocks the chart."],
    buyStreak: ["Our top story, {n} buys in {sec} seconds."],
    sellStreak: ["Tonight's headline, {n} consecutive sells."],
    pump: ["Markets react. {pct} in five minutes."],
    dump: ["Turbulence. {pct} in five minutes. We'll keep you updated."],
    ath: ["Historic moment. {mcap}, a new all time high."],
    drawdown: ["Our analysts note {dd} off the high."],
    recovery: ["Recovery story tonight. Up {pct} from {low}."],
    milestone: ["Milestone. {milestone}. Cameras rolling."],
    quiet: ["A slow news cycle. {mcap}. We go to the weather. It's also quiet."],
  },
  hacker: {
    signoff: ["// end log", "sudo hold", "exit 0."],
    launch: ["Process spawned. {ticker} running at {mcap}. Watching every packet."],
    buy: ["Incoming tx. {sol}. Looks clean.", "{sol} buy. Logged."],
    sell: ["{sol} sell. Grep says paper hands.", "Outgoing tx, {sol}. Noted in the logs."],
    whaleBuy: ["Large packet inbound. {sol}. That's not a bot. Probably.", "{sol} buy. That wallet has root."],
    whaleSell: ["{sol} exit. Somebody pulled the plug."],
    buyStreak: ["{n} buys, {sec} seconds. Pattern recognized."],
    pump: ["{pct}. The chart just overclocked."],
    dump: ["{pct}. Segfault in the candle."],
    ath: ["New high, {mcap}. Committing to main."],
    drawdown: ["{dd} under the high. Rolling back is not an option."],
    recovery: ["Recovered from {low}. Patch deployed."],
    quiet: ["Mempool quiet. Too quiet. Running ping.", "No packets. Idling at {mcap}."],
  },
  scientist: {
    signoff: ["Fascinating.", "For science.", "Recording."],
    launch: ["Experiment {ticker} has begun. Initial reading, {mcap}."],
    buy: ["Specimen bought {sol}. Recording.", "{sol} buy. Hypothesis supported."],
    sell: ["{sol} sell. An outlier. Probably."],
    whaleBuy: ["{sol}! Statistically significant!", "A {sol} buy. Peer review will be thrilled."],
    whaleSell: ["{sol} sold. Contaminated sample."],
    pump: ["{pct} in five minutes. Exothermic reaction."],
    dump: ["{pct}. The experiment is, uh, educational."],
    ath: ["New maximum, {mcap}. Publishing immediately."],
    drawdown: ["{dd} below peak. Data is data."],
    recovery: ["Recovery of {pct} from {low}. Reproducible? Unknown."],
    quiet: ["Low activity. Taking field notes at {mcap}."],
  },
  alien: {
    signoff: ["Earth is strange.", "Transmitting home.", "Fascinating primates."],
    launch: ["Greetings. I have taken the form of {ticker}. Your currency says {mcap}."],
    buy: ["A human gave {sol}. I accept this ritual.", "{sol}. Your species calls this a buy."],
    sell: ["{sol} sold. Why do humans flee?"],
    whaleBuy: ["{sol}! Large Earth creature detected!"],
    whaleSell: ["The large one left with {sol}. Unsettling."],
    pump: ["{pct}. On my planet this is called Tuesday."],
    dump: ["{pct}. Your gravity is very strong."],
    ath: ["{mcap}. Highest altitude yet."],
    drawdown: ["{dd} lower than before. Earth physics, I assume."],
    recovery: ["We rise again from {low}."],
    quiet: ["The humans are sleeping. I will continue observing at {mcap}."],
  },
  meme: {
    signoff: ["Classic.", "No notes.", "Peak content."],
    launch: ["Hi. I'm {ticker}. I exist now. {mcap}. This is canon."],
    buy: ["{sol} buy. Absolute legend.", "Bought {sol}. Respect."],
    sell: ["{sol} sell. Okay, that one's going in the cringe compilation."],
    whaleBuy: ["{sol}. That's a lot of sol for a joke.", "BIG {sol}. Somebody's mom is gonna find out."],
    whaleSell: ["{sol} sold. Ratio'd by my own chart."],
    pump: ["{pct}. We're so back."],
    dump: ["{pct}. It's so over. Until it isn't."],
    ath: ["{mcap}. Main character energy."],
    drawdown: ["{dd} below the top. Plot twist."],
    recovery: ["Back from {low}. We're so back."],
    quiet: ["Dead chat. Somebody say something funny.", "Sitting at {mcap}, vibing."],
  },
};

export const MEMORY_CALLBACKS = {
  drawdown: ["We were at {ath} {ago} ago. I remember everything.", "{ath}, {ago} ago. Don't think I forgot."],
  dump: ["Peak was {ath}, {ago} ago. I remember."],
  recovery: ["The high is still {ath}. I remember where we were.", "Not {ath} yet. But I remember the way."],
  ath: ["Previous high was {prevAth}. Retired.", "Old record, {prevAth}. Replaced."],
  whaleBuyBigger: ["Still smaller than the {largest} buy from earlier, though."],
  whaleBuyRecord: ["Largest buy I've seen so far."],
  repeatWallet: ["Same wallet again. Trade number {walletN}.", "I recognize that wallet. {walletN} trades now."],
  milestone: ["Launch was {launch}. Look at us now."],
  quiet: ["Launched at {launch}. High of {ath}. Now {mcap}.", "Biggest buy so far was {largest}."],
};

export const EMOTION = {
  launch: "CELEBRATING", buy: "SMUG", sell: "DISAPPOINTED", whaleBuy: "EXCITED", whaleSell: "SHOCKED",
  buyStreak: "EXCITED", sellStreak: "ANGRY", pump: "EXCITED", dump: "SHOCKED", ath: "CELEBRATING",
  drawdown: "DISAPPOINTED", recovery: "SMUG", milestone: "CELEBRATING", quiet: "THINKING", volume: "EXCITED",
  aggBuy: "EXCITED", aggSell: "ANGRY", aggMixed: "THINKING", custom: "SPEAKING",
};

export const EMOTION_OVERRIDES = {
  villain: { sell: "ANGRY", whaleSell: "ANGRY", buy: "SMUG" },
  wallstreet: { sell: "SMUG", dump: "DISAPPOINTED" },
  chaotic: { sell: "SHOCKED", buy: "EXCITED" },
  robot: { whaleSell: "SHOCKED" },
};

export const EVENT_CATEGORY = {
  TOKEN_LAUNCHED: "launch", BUY: "buy", SELL: "sell", LARGE_BUY: "whaleBuy", LARGE_SELL: "whaleSell",
  BUY_STREAK: "buyStreak", SELL_STREAK: "sellStreak", PRICE_SURGE: "pump", PRICE_DROP: "dump", NEW_ATH: "ath",
  ATH_DRAWDOWN: "drawdown", RECOVERY: "recovery", MARKET_CAP_MILESTONE: "milestone", QUIET_MARKET: "quiet", VOLUME_SPIKE: "volume",
};
